name: redis-plugin
description: Pluglin responsável por adicionar as configuações básicas do redis
display-name: redis-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Connection Host
    type: text
    name: host_name
    default: localhost
  - label: Connection Port
    type: text
    name: port
    default: 6379
  - label: Configuration path. Ex - br.com.org.project.application.config
    type: text
    name: config_path

computedInputs:
  "path": "src/main/kotlin/{{inputs.config_path | replace('.','/')}}"

hooks:
  - type: edit
    trigger: after-render
    path: pom.xml
    changes:
      - search:
          string: </dependencies>
          insert-before:
            snippet: snippets/pom-config.xml
          when:
            not-exists-snippet: snippets/pom-config.xml
  - type: edit
    trigger: after-render
    path: src/main/resources/application.properties
    changes:
      - insert:
          line: -1
          snippet: snippets/application.properties
